package Entities

case class ExecutionParameters(var lsFlag: Int,
                               var nnLs: Int,
                               var nAnts: Int,
                               var nnAnts: Int,
                               var rho: Double,
                               var alpha: Double,
                               var beta: Double,
                               var q0: Double,
                               var maxTries: Int,
                               var maxTours: Int,
                               var maxTime: Double,
                               var optimal: Int,
                               var asFlag: Int,
                               var dlbFlag: Int,
                               var easFlag: Int,
                               var rasFlag: Int,
                               var mmasFlag: Int,
                               var bwasFlag: Int,
                               var acsFlag: Int,
                               var trailMax: Int,
                               var trailMix: Int,
                               var ugb: Int,
                               var trail0: Double,
                               var rasRanks: Int,
                               var elitistRanks: Int,
                               var tsplibfile: String)
